packages:
  - "apps/*"
  - "packages/*"
  - "packages/ui/*"
  - "apps/backend/services/*"
  - "apps/frontend/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
