export const KAFKA_TOPICS = {
  AUTH: {
    USER_REGISTERED: "auth.user.registered",
    USER_LOGIN: "auth.user.login",
    USER_LOGOUT: "auth.user.logout",
    OTP_REQUESTED: "auth.otp.requested",
    OTP_VERIFIED: "auth.otp.verified",
    EMAIL_VERIFICATION_REQUESTED: "auth.email_verification.requested",
    EMAIL_VERIFIED: "auth.email.verified",
    PASSWORD_CHANGED: "auth.password.changed",
    PASSWORD_RESET_REQUESTED: "auth.password_reset.requested",
    PASSWORD_RESET_COMPLETED: "auth.password_reset.completed",
    TWO_FA_ENABLED: "auth.2fa.enabled",
    TWO_FA_DISABLED: "auth.2fa.disabled",
    TWO_FA_VERIFIED: "auth.2fa.verified",
    REFRESH_TOKEN_ISSUED: "auth.refresh_token.issued",
    REFRESH_TOKEN_REVOKED: "auth.refresh_token.revoked",
    SESSION_EXPIRED: "auth.session.expired",
  },

  USER: {
    CREATED: "user.created",
    UPDATED: "user.updated",
    DELETED: "user.deleted",
    SUSPENDED: "user.suspended",
    ACTIVATED: "user.activated",
    FOLLOWED: "user.followed",
    UNFOLLOWED: "user.unfollowed",
    BLOCKED: "user.blocked",
    UNBLOCKED: "user.unblocked",
    MUTED: "user.muted",
    UNMUTED: "user.unmuted",
    PROFILE_VIEWED: "user.profile.viewed",
    VERIFIED_BADGE_GRANTED: "user.verified_badge.granted",
    VERIFIED_BADGE_REVOKED: "user.verified_badge.revoked",
  },

  TWEET: {
    CREATED: "tweet.created",
    UPDATED: "tweet.updated",
    DELETED: "tweet.deleted",
    LIKED: "tweet.liked",
    UNLIKED: "tweet.unliked",
    RETWEETED: "tweet.retweeted",
    UNRETWEETED: "tweet.unretweeted",
    REPLIED: "tweet.replied",
    QUOTED: "tweet.quoted",
    BOOKMARKED: "tweet.bookmarked",
    UNBOOKMARKED: "tweet.unbookmarked",
    VIEWED: "tweet.viewed",
    SHARED: "tweet.shared",
  },

  NOTIFICATION: {
    EMAIL_SEND: "notification.email.send",
    EMAIL_SENT: "notification.email.sent",
    EMAIL_FAILED: "notification.email.failed",
    PUSH_SEND: "notification.push.send",
    PUSH_SENT: "notification.push.sent",
    PUSH_FAILED: "notification.push.failed",
    SMS_SEND: "notification.sms.send",
    SMS_SENT: "notification.sms.sent",
    SMS_FAILED: "notification.sms.failed",
    CREATED: "notification.created",
    READ: "notification.read",
    DELETED: "notification.deleted",
  },

  MESSAGE: {
    SENT: "message.sent",
    DELIVERED: "message.delivered",
    READ: "message.read",
    DELETED: "message.deleted",
    UPDATED: "message.updated",
    CONVERSATION_CREATED: "message.conversation.created",
    CONVERSATION_DELETED: "message.conversation.deleted",
    TYPING_STARTED: "message.typing.started",
    TYPING_STOPPED: "message.typing.stopped",
    PARTICIPANT_ADDED: "message.participant.added",
    PARTICIPANT_REMOVED: "message.participant.removed",
  },

  MEDIA: {
    UPLOADED: "media.uploaded",
    PROCESSING: "media.processing",
    PROCESSED: "media.processed",
    FAILED: "media.failed",
    DELETED: "media.deleted",
  },

  SEARCH: {
    QUERY_PERFORMED: "search.query.performed",
    TRENDING_UPDATED: "search.trending.updated",
    INDEX_UPDATED: "search.index.updated",
  },

  TIMELINE: {
    UPDATED: "timeline.updated",
    CACHE_INVALIDATED: "timeline.cache.invalidated",
  },

  LIST: {
    CREATED: "list.created",
    UPDATED: "list.updated",
    DELETED: "list.deleted",
    MEMBER_ADDED: "list.member.added",
    MEMBER_REMOVED: "list.member.removed",
    FOLLOWED: "list.followed",
    UNFOLLOWED: "list.unfollowed",
  },

  SPACE: {
    CREATED: "space.created",
    STARTED: "space.started",
    ENDED: "space.ended",
    UPDATED: "space.updated",
    SPEAKER_JOINED: "space.speaker.joined",
    SPEAKER_LEFT: "space.speaker.left",
    LISTENER_JOINED: "space.listener.joined",
    LISTENER_LEFT: "space.listener.left",
    RECORDING_STARTED: "space.recording.started",
    RECORDING_STOPPED: "space.recording.stopped",
  },

  MODERATION: {
    CONTENT_REPORTED: "moderation.content.reported",
    USER_REPORTED: "moderation.user.reported",
    REPORT_REVIEWED: "moderation.report.reviewed",
    ACTION_TAKEN: "moderation.action.taken",
    CONTENT_FLAGGED: "moderation.content.flagged",
    APPEAL_SUBMITTED: "moderation.appeal.submitted",
  },

  ANALYTICS: {
    EVENT_TRACKED: "analytics.event.tracked",
    IMPRESSION_RECORDED: "analytics.impression.recorded",
    ENGAGEMENT_RECORDED: "analytics.engagement.recorded",
  },
} as const;
