import type { Metadata } from "next";
import "../globals.css";
import "../../theme/mui.config";
import { HomeThemeProvider } from "@/providers/home.theme.provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

import localFont from "next/font/local";
import ModeSwitch from "@/components/global/mode-switch";
import { ThemeProvider } from "@/providers/theme.provider";
import LayoutProvider from "./layout.provider";

const chirp = localFont({
  src: [
    {
      path: "../../../public/fonts/chirp-regular-web.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/chirp-bold-web.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-chirp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.variable} antialiased`}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
